(
    /* Déclarations et appels */
    let
        /* undeclaredType */
        type rec = {a : undeclaredType} /* Ajouté dans la TDS quand même sans le mauvais field */
        type arr = array of undeclaredType /* Pas ajouté car pas de type */
        type aliasType = undeclaredType
        function f(x : undeclaredType, param1 : int) : undeclaredType = (let var varInUndeclaredFct := 1 in end)
        function f(x : int, param2 : int) : undeclaredType = (1)
        function f(x : undeclaredType, param3 : int) = (1) /* Ajouté dans la TDS quand même sans paramètre */
        var test : undeclaredType := 2


        type arr1 = array of int
        type rec1 = {a : arr1}
        function f1(x : rec1) = ()
        var x1 := arr1[1] of 1
        var t1 := rec1{a = x1}
        var N : int := 2

        /* undelcaredId */
        var y1 := undeclaredFct(undeclaredParam)
        var y1 := undeclaredRec{undeclaredField = undeclaredVar}
        var y1 := undeclaredArrVar[undeclaredLength] of undeclaredType
        var y1 := undeclaredRecVar.undeclaredField /* id pas défini mais on spécifie pas qu'on voulait un record */
        var y1 := t1.undeclaredField
        var y1 := undeclaredArrVar[0]
        var y1 := rec1{undeclaredField = undeclaredVar} /* Ajouté dans la TDS quand même */

        /* Erreurs type d'affectation en déclaration */
        function f2(x : int) : int = ("a")
        var z1 : rec1 := "string"
        var test := f1(z1)
        var a := f2("a")
        var b : arr1 := rec1{a = x1}
        var c : rec1 := rec1{a = 2}
        var d : arr1 := arr1[N] of x1
    in         
        undeclaredVar := arr1["a"] of "b"; /* Continue l'analyse */
        
        /* contrôles sur l'id des fonctions */
        x1(1);
        f1 := 2;
        x1 := arr1[N] of f1;
        N := f1[0];
        x1 := f1.a
    end;



    /* for while ifthen(else) */
    for i := 1 to 5 do (
        let 
            /* TDS vide */
        in 
            i := 0;
            for i := "a" to "b" do()
        end;

        i := 0;

        1
    );


    while "a" do (
        1
    );


    if "a" then (
        1
    );


    if "a" then (
        1
    )
    else (
        "b"
    );


    break;



    /* Erreurs paramètres des fonctions en appel (type et nombre) */
    let 
        function f1(x : int) = ()
        function f2() : int = (1)

        var x := f1("a", 1)
        var y := f1()     
        var z := f2(2)
    in
    end;

    /* Erreurs fields des records en appel (type et nombre) */
    let
        type rec1 = {f : int}

        var x := rec1{g = 1, f = "a"}
        var y := rec1{}
    in
    end;




    /* Erreurs redéclaration dans espace de nommage */
    let
        type arr = array of int
        type rec = {a : int}
        var x := 1
        function f(a : int) = ()

        /* signature différente */
        type arr = array of string
        type rec = {b : int}
        var x := "a"
        function f(b : string) = ()

        /* swap type */
        type arr = {a : int}
        type rec = array of int
        var f := 1
        function x(c : int) = ()

        /* changement d'espace de nommage (pas d'erreurs) */
        type x = array of int
        type f = {a : int}
        var arr := 1
        function rec(d : int) = ()
    in
    end;


    /* Erreurs paramètres et fields identiques */
    let
        type rec = {a : int, a : string}
        function f(a : int, a : string) = ()
    in
    end;



    /* Erreur affectation à une expression car LL(1) */
    (1) := 2;





    /* Opérateurs binaires */
    1 + "a";
    1 - "a";
    1 * "a";
    1 / "a";
    1 | "a";
    1 & "a";
    1 = "a";
    1 <> "a";
    1 > "a";
    1 < "a";
    1 >= "a";
    1 <= "a"



    /*  */
)