@startuml

class Tds{
    int numeroImbrication
    int identifiant
    int identifiantTablePrecedente
    void add()
    void toString()
}

abstract Entry{
    String symbol
    int size

    void toString()
}

class VariableEntry{
    int decalage
}
class FunctionEntry
abstract TypeEntry
abstract VarFuncEntry


Tds - "*"Entry

Entry <|-- VarFuncEntry
Entry <|-- TypeEntry
VarFuncEntry <|-- VariableEntry
VarFuncEntry <|-- FunctionEntry
TypeEntry <|-- ArrayEntry
TypeEntry <|-- RecordEntry

RecordEntry -- "*"Field 
FunctionEntry -- "*"Parameter




@enduml