/* Déclaration de variable array se fait par valeur (copie) */
/* Record */

let
    var N := 2

    type student = {name : string, age : int}
    type class = array of student

    var steven := student{name = "Steven", age = 21}
    var crew := class[N] of steven /* crew[1] et crew[2] sont indépendants */
in
    crew[1].name := "Wenjia";
    
    if crew[2].name = "Wenjia" then (
        print(0)
    );
    if crew[2].name = "Steven" then (
        print(1)
    )
end