let
    type intArray = array of int
    type listCouple = {L1 : intArray,L2 : intArray}
    var L := intArray[10] of 0
    function fusion(couple : listCouple,len1 : int, len2 : int) =
        let 
            var L := intArray[len1 +len2] of 0 
            var i1 := 0
            var i2 := 0
        in
            (while i1 <len1 & i2 < len2 do
                if i1 = len1 then(
                    L[i1+i2] := couple.L2[i2];
                    i2 := i2 +1
                )
                else(
                    if i2 = len2 then(
                        L[i1+i2] := couple.L1[i1];
                        i1 := i1+1
                    )
                    else(
                        if couple.L1[i1] < couple.L2[i2]
                        then(
                            L[i1+i2] := couple.L1[i1];
                            i1 := i1 + 1
                        )
                        else(
                            L[i1+i2] := couple.L2[i2];
                            i2 := i2 + 1
                        )
                    )
                );
            L)
        end
    /*function separe(L : intArray,len : int) : listCouple =
        let var couple = listCouple*/

in ()
end

                

