let 
    type list = {head : int, tail : list}
    type coupleList = {L1 : list, L2: list}
    
    /* L = (5, 2, 3, 1, 4, 6) */
    var L := list{head = 5, tail = list{head = 2, tail = list{head = 3, tail = list{head = 1, tail = list{head = 4,tail = list{head = 6, tail = nil}}}}}}

    var sortedList : list := nil
    var list_ptr : list := nil

    function separe(L : list) : coupleList =
        if L = nil then(
            coupleList{L1 = nil, L2 = nil}
        )
        else(
            if L.tail = nil then (
                coupleList{L1 = list{head = L.head, tail = nil}, L2 = nil}
            )
            else(
                let
                    var couple := separe(L.tail.tail)
                in
                    coupleList{L1 = list{head = L.head, tail = couple.L1},L2 = list{head=L.tail.head, tail = couple.L2}}
                end
            )
        )

    function fusion(couple : coupleList) : list =
        if couple.L1 = nil then(
            couple.L2
        )
        else (
            if couple.L2 = nil then(
                couple.L1
            )
            else(
                if couple.L1.head < couple.L2.head then(
                    list{head = couple.L1.head, tail = fusion(coupleList{L1 = couple.L1.tail, L2 = couple.L2})}
                )
                else(
                    list{head = couple.L2.head, tail = fusion(coupleList{L1 = couple.L1, L2 = couple.L2.tail})}
                )
            )
        )
        
    function triFusion(L : list) : list =
        if L = nil | L.tail = nil then(
            L
        )
        else(
            let 
                var couple := separe(L)
            in
                fusion(coupleList{L1 = triFusion(couple.L1), L2 = triFusion(couple.L2)})
            end
        )
in
    list_ptr := L;
    while list_ptr <> nil do (
        print(list_ptr.head);
        list_ptr := list_ptr.tail
    );

    print(1111111);

    sortedList := triFusion(L);

    list_ptr := sortedList;
    while list_ptr <> nil do (
        print(list_ptr.head);
        list_ptr := list_ptr.tail
    )
end


